### ISSUE TITLE
Extension broken by wire update

### ISSUE THREAD

**Issue by Vurv78** [Linus045/e2_vgui_core#22]
As of https://github.com/wiremod/wire/pull/2372, `e2_extpp_pass1` and `e2_extpp_pass2` no longer exist, and have been changed to `E2Lib.ExtPP.Pass1` and `E2Lib.ExtPP.Pass2` respectively, breaking this extension. Should've searched github to see if anyone used these, but I didn't think anyone would've at the time

**Comment by Linus045** [comment]
Thanks for reporting, I will look into it.
Seems like an easy fix
