### ISSUE TITLE
dmodelpanel(xdk): the click doesn't work?

### ISSUE THREAD

**Issue by enrico002** [Linus045/e2_vgui_core#30]
Hi,
using the usual test if( ID == Model:id() ) { Number = 1 String = Model:getModel(Player) } the click doesn't seem to work for the dmodelpanel(xdk) object. The Number variable nor the String are not updated.
Any action seems ignored. Am I doing something wrong?

**Comment by Linus045** [comment]
No your code is correct.

It seems that I forgot to implement the OnClick event for DModelPanel. Therefore clicking on the model does nothing at the moment. Thank you for bringing this to my attention.

I will implement the OnClick event to fix this.
