### ISSUE TITLE
"xdk:setLookAng(A)"function, listed on wiki, doesn't exist.

### ISSUE THREAD

**Issue by Mihoshika** [Linus045/e2_vgui_core#4]
https://github.com/Linus045/e2_vgui_core/wiki/Supported-Panels-and-Functions#DModelPanel

**Comment by Linus045** [comment]
This function was never implemented.
I added it to the experimental branch (fde7edd758bb83b0c04b3cf3cb4e17811f394198), it will soon get merged into the workshop branch.
