### ISSUE TITLE
dlistview now working/showing up

### ISSUE THREAD

**Issue by CalocoDoesGit** [Linus045/e2_vgui_core#6]
I'm trying to get a list to work, and have followed the example proved by the [gmod wiki](https://wiki.facepunch.com/gmod/DListView) as you haven't yet updated [your wiki here on github](https://github.com/Linus045/e2_vgui_core/wiki/Examples-for-different-types#dlistview) for it.

All of the functions seem to exist and validate fine inside the e2 editor.
But when I open the VGUI pannel it won't display the list I have created.

Am I doing something wrong or is it an issue on the addon's end?
(other elements like dbutton, dcombobox and dlabel work fine)

```
@persist Frame:dframe ListSetupStations:dlistview

    Frame = dframe(1)
    Frame:setTitle("Cal's Destination Boards GUI")
    Frame:setSize(500,500)
    Frame:center()
    Frame:makePopup()
    Frame:create()
    
    ListSetupStations = dlistview(27, Frame)
    ListSetupStations:setPos(10,10)
    ListSetupStations:setSize(80,80)
    ListSetupStations:addColumn("Name")
    ListSetupStations:addColumn("Type")
            
    ListSetupStations:addLine("Wolfram", "Terminal")
    ListSetupStations:addLine("Rockfort", "Terminal")
```

Also, is `SetMultiSelect` supported? If not: will it be?

**Comment by Linus045** [comment]
@CalocoDoesGit 
You need to call the create() function for every element you want to display. It basically tells the e2 (which runs serverside) to create the element (on the clientside).

So adding `ListSetupStations:create()` should fix it.
(Remember to use modify() instead to change things after you created them).
See basic structure that every element has to follow in the introduction [here](https://https://github.com/Linus045/e2_vgui_core/wiki/E2Helper-Entries-%5BAutogenerated%5D)

If that still doesn't work I will have a closer look at it in the next few days, currently busy.
I will also try to expand the examples.


Regarding multiselect, it is implemented and should work.
See all [DListView functions here](
https://github.com/Linus045/e2_vgui_core/wiki/E2Helper-Entries-%5BAutogenerated%5D#dlistviewxdv).

To grab the selected values I recommend to utilize the vguiClkValuesTable() function as mentioned [here](https://github.com/Linus045/e2_vgui_core/wiki/E2Helper-Entries-%5BAutogenerated%5D#general-functions)

**Comment by CalocoDoesGit** [comment]
Thanks for the response.

It's always the 1 extremely obvious thing you completely forget..... -_-

Will get back to you if I have any other issues.

**Comment by Linus045** [comment]
I will close this issue then.
If you still have problems with the listview feel free to reopen this issue again.

If you have a different problem please create a new issue so it's not all mixed up for other people who have similar problems.
