### ISSUE TITLE
Can't block or allow player

### ISSUE THREAD

**Issue by rush93** [Linus045/e2_vgui_core#7]
If a player have a `'` in they'r name we can't remove or add them in our buddies via the menu.

**Comment by Linus045** [comment]
Hmm that is weird, iirc I only use the Steam-ID to add/remove players from the buddy list.
Maybe you can use the console command as a workaround.

I'll try to look into it in the next days.

**Comment by Linus045** [comment]
The problem was that i didn't escape usenames when i added the blocked/buddied user to the local database.
974cc2a9cd3b2a928a6782142601f8bcee39cf15 should fix the problem.
I know escape the username and show proper error messages if it fails.
